# [INFO & WARNING]
# THIS IS AN EDITABLE YAML PAGE, MAKE SURE TO KEEP ALL FORMATTING VALID.
# ONCE YOU HAVE MADE YOUR CHANGES, PRESS <Save> UNDER THE TOOLBAR.
# ALL CHANGES REQUIRE RELAUNCHING THE APPLICATION TO TAKE EFFECT.

# Karatasi
# author: wiicart
# repo: github.com/wiicart/Karatasi

# Timeout Duration
# How long should the application wait for a webpage to respond (milliseconds)?
timeout: 10000

# Enable Local File Editor
# For local files (opened with local://), should the browser provide a basic editor?
allow-edits: false